sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
  - STACK_YAML=stack.yaml
  - STACK_YAML=stack-ghc-8.yaml

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

script:
  - stack setup
  - stack build --ghc-options -Werror
  - stack test --ghc-options -Werror


cache:
  directories:
    - $HOME/.stack
