name: generics-eot

dependencies:
  - base

extra-source-files:
  - README.md

ghc-options:
  "-Wall -fno-warn-name-shadowing"

library:
  exposed-modules:
    - Generics.Eot
    - Generics.Eot.Tutorial
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
      - examples
    dependencies:
      - hspec
      - QuickCheck
      - interpolate
      - doctest

  quickcheck:
    main: Spec.hs
    source-dirs:
      - test/quickcheck
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - shake
      - directory
      - filepath
      - QuickCheck
