name: generics-eot

dependencies:
  - base

ghc-options:
  "-Wall -fno-warn-name-shadowing"

library:
  exposed-modules:
    - Generics.Eot
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
      - examples
    dependencies:
      - hspec
      - QuickCheck

  quickcheck:
    main: Spec.hs
    source-dirs:
      - test/quickcheck
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - shake
      - directory
      - filepath
      - QuickCheck
